### ISSUE TITLE
所有配置项目用记本事打开之后不换行的问题

### ISSUE THREAD

**Issue by xiaobai99** [Qitmeer/qitmeer-miner#106]
**BUG描述**
配置文件打开之后不换行

**重现步骤**
可能出现此问题的原因:
1. WIN7系统下打开有出现此问题现象
2. 电脑文本编辑器出错会出现此问题

**预期的行为**
WIN10系统一般不会出现此类问题，

**截屏如下**
![a3b647707dc497f3c20152aacafe8cfa36b80cdf_2_690x113](https://user-images.githubusercontent.com/48641426/68541898-4e556b80-03e0-11ea-870c-9d5c5fd56721.png)

**环境信息 (请尽可能提供完整信息):**
- 操作系统 [e.g. Windows 7]
- 显卡 [e.g. GTX 1070]

**Comment by jamesvan2019** [comment]
> **BUG描述**
> 配置文件打开之后不换行
> 
> **重现步骤**
> 可能出现此问题的原因:
> 
> 1. WIN7系统下打开有出现此问题现象
> 2. 电脑文本编辑器出错会出现此问题
> 
> **预期的行为**
> WIN10系统一般不会出现此类问题，
> 
> **截屏如下**
> ![a3b647707dc497f3c20152aacafe8cfa36b80cdf_2_690x113](https://user-images.githubusercontent.com/48641426/68541898-4e556b80-03e0-11ea-870c-9d5c5fd56721.png)
> 
> **环境信息 (请尽可能提供完整信息):**
> 
> * 操作系统 [e.g. Windows 7]
> * 显卡 [e.g. GTX 1070]

请下载下载`SUBLIME ` 或者 `NOTEPAD++` 等文本编辑软件打开

**Comment by xiaobai99** [comment]
**解决方法如下：**
下载notepad2文本编辑器来修改配置
下载地址：链接[https://pan.baidu.com/s/1yAH34CU2oa0Xv0eHCBHPIg](url)接取码：33d4
如图：
![511cd58103a3f07cfe54e146eaf8eb86b6348177_2_433x500](https://user-images.githubusercontent.com/48641426/68541939-c1f77880-03e0-11ea-9444-0e7618ae7046.jpeg)

**Comment by JeremyChen01** [comment]
https://www.qitmeertalk.org/uploads/default/original/1X/e50ab1b2126b645481d1278cfa36e0bd8195a40f.jpeg
