### ISSUE TITLE
打开挖矿软件后提示错误

### ISSUE THREAD

**Issue by JeremyChen01** [Qitmeer/qitmeer-miner#107]
**BUG描述**
打开挖矿软件后提示系统错误

**截屏如下**
![e50ab1b2126b645481d1278cfa36e0bd8195a40f](https://user-images.githubusercontent.com/48641416/68542233-6b406d80-03e5-11ea-84b3-d17c38e20497.jpeg)

**环境信息 :**
- 操作系统 [e.g. Windows 10]
- 显卡 [NVIDIA GEFORCE 920MX]

**Comment by jamesvan2019** [comment]
> **BUG描述**
> 打开挖矿软件后提示系统错误
> 
> **截屏如下**
> ![e50ab1b2126b645481d1278cfa36e0bd8195a40f](https://user-images.githubusercontent.com/48641416/68542233-6b406d80-03e5-11ea-84b3-d17c38e20497.jpeg)
> 
> **环境信息 (请尽可能提供完整信息):**
> 
> * 操作系统 [e.g. Windows 10]
> * 显卡 [NVIDIA GEFORCE 920MX]

请下载`驱动精灵`或者`驱动人生` 安装显卡驱动,如果是N卡可安装`cuda`

**Comment by dindinw** [comment]
@JeremyChen01 该问题是否已经解决？
