### ISSUE TITLE
qitmeer-miner --version 标签无效

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qitmeer-miner#110]
**BUG描述**
qitmeer-miner --version 标签无效，无法查看版本

**重现步骤**
如何可以使该BUG出现的步骤:
直接使用命令 `qitmeer-miner --version` 

 可以看到错误如下...

```
$ ./qitmeer-miner --version
2019-11-18 11:27:13.431 [Error] unknown flag `version'
2019-11-18 11:27:13.431 [Error] Usage to see  ./qitmeer-miner -h
```

**预期的行为**
报错信息显示 没有 version 这个flag，好像是因为miner本身就没有设置这个标签，希望能设置个version标签，以方便查看版本信息

**截屏(如有)**
![image](https://user-images.githubusercontent.com/32875657/69022562-ab5fab80-09f6-11ea-84e3-cb40b907cdc8.png)

**系统环境**
windows 10

**Comment by jamesvan2019** [comment]
新版本 应该加过了 从0.2.4开始加的

**Comment by dindinw** [comment]
fixed

**Comment by blocklee** [comment]
> fixed

ok，I will see.
