### ISSUE TITLE
The msg display is not correct for CUDA GPU support

### ISSUE THREAD

**Issue by dindinw** [Qitmeer/qitmeer-miner#133]
The msg show `doesn't support CUDA`, but CUDA is working. 

### Screen shoot
![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/1134993/70841779-0d75ca00-1e58-11ea-80be-f2580eaab552.jpeg)

**Comment by jamesvan2019** [comment]
> The msg show `doesn't support CUDA`, but CUDA is working.
> 
> ### Screen shoot
> ![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/1134993/70841779-0d75ca00-1e58-11ea-80be-f2580eaab552.jpeg)

this computer may have two GPU platform
