### ISSUE TITLE
这到底是怎么了？ ？？？？？？？？？？

### ISSUE THREAD

**Issue by bbkbk222** [Qitmeer/qitmeer-miner#135]
![image](https://user-images.githubusercontent.com/48194218/70874527-780c3e80-1fed-11ea-8a76-6f90ab33d118.png)
使用都是最新的节点以及软件，

**Comment by bbkbk222** [comment]
调整  trimmerTimes=16数值后 算力会维持一段时间继续下降

**Comment by bbkbk222** [comment]
![image](https://user-images.githubusercontent.com/48194218/70874748-6bd4b100-1fee-11ea-80b5-a83f69fa8649.png)
1660 6G显存显卡挖大图提示407

**Comment by bbkbk222** [comment]
![image](https://user-images.githubusercontent.com/48194218/70897443-9c880b00-202d-11ea-9ff4-912c6a77bfdb.png)

**Comment by blocklee** [comment]
> 调整 trimmerTimes=16数值后 算力会维持一段时间继续下降

你还是用 trimmerTimes=14 吧

**Comment by blocklee** [comment]
> ![image](https://user-images.githubusercontent.com/48194218/70874748-6bd4b100-1fee-11ea-80b5-a83f69fa8649.png)
> 1660 6G显存显卡挖大图提示407

卸载旧显卡驱动，安装最新驱动，430版本以上试试。另外，挖大图需要可用内存在6g左右

**Comment by jamesvan2019** [comment]
使用最新版 解决这个算力显示问题

**Comment by dindinw** [comment]
@bbkbk222 I believe its a resolved problem, closed for new, please reopen it if it is still an issue.
