### ISSUE TITLE
miner-0.3.4运行时自动停止

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qitmeer-miner#137]
**BUG描述**
miner-0.3.4在使用过程中，出现自动停止，不工作的的情况。在我发现后，在窗口内按下 enter 键后，又开始工作了。从以下截图中的时间可以看出来。

**重现步骤**
运行0.3.4

**截屏(如有)**
如果有，可以使用截屏来帮助描述问题所在。
![image](https://user-images.githubusercontent.com/32875657/71052650-f94b0900-2186-11ea-90b8-b40876dfc87b.png)

**环境信息 (请尽可能提供完整信息):**
- 操作系统 [e.g. Windows 10]
- 显卡 [e.g. GTX 1070]
  你可以使用`./qitmeer-miner -l`命令获得输出粘贴在这里，如:
  ```
>qitmeer-miner.exe -l
2019-12-18|11:17:35.057 [INFO ] [GPU Devices List]:                 module=miner
2019-12-18|11:17:35.379 [INFO ] Platform:NVIDIA CUDA DeviceID:# 0 DeviceName:GeForce 920MX MaxAllocSize:512.00 MB MaxMemSize:2048.00 MB module=miner
2019-12-18|11:17:35.384 [INFO ] Platform:Intel(R) OpenCL DeviceID:# 1 DeviceName:Intel(R) HD Graphics 620 MaxAllocSize:2048.00 MB MaxMemSize:3215.35 MB module=miner
  ```

- qitmeer-miner 版本 [e.g. 0.2.4]
  你可以使用`./qitmeer-miner --version`命令获得输出粘贴在这里，如:
  ```
>qitmeer-miner.exe --version
Qitmeer Miner Version:0.3.4(Go version go1.12.1)
  ```

- 命令行参数或配置文件 
  例如：
  ```
  #### Device Config ####
  use_devices=0

  #### Log Config ####
  # specify a file to write miner log
  log_level=debug

  #### Cuckoo Config ####
  edge_bits=24
  trimmerTimes=14

  #### Blake2bd Config ####
  # Intensities (the work size is 2^intensity) up to device
  intensity=24
   worksize=256

  #### Other Config ####
  max_sig_count=4000
  ```

**其它备注**
任何其它需要说明的问题。

**Comment by jamesvan2019** [comment]
这个问题没有重现，请确认是否误操作，目前可重现此问题的方式，将鼠标选中cmd 界面，程序将暂停

**Comment by dindinw** [comment]
@blocklee I believe it is a usage case,  close for now,  please reopen it if any newly-added proof or steps on this issue that can be reproduced.
