### ISSUE TITLE
挖矿闪退，报错

### ISSUE THREAD

**Issue by foqer** [Qitmeer/qitmeer-miner#138]
**BUG描述**
挖矿闪退，报错

**重现步骤**
必现

**预期的行为**
不应该有报错信息

**截屏(如有)**
不知道怎么弄。
我复制下报错信息：
C:\download\win-miner>qitmeer-miner.exe --version
Qitmeer Miner Version:0.3.4(Go version go1.12.1)

C:\download\win-miner>qitmeer-miner.exe -C solo.conf
2019-12-18|15:19:05.425 [INFO ] Platform:NVIDIA CUDA DeviceID:# 0 DeviceName:GeForce RTX 2070 SUPER MaxAllocSize:2048.00 MB MaxMemSize:8192.00 MB module=miner
2019-12-18|15:19:05.673 [INFO ] solo miner start                    module=miner
2019-12-18|15:19:06.201 [DEBUG] ==============Mining Cuckaroo: deviceID:0 edge bits:24 trimmerTimes:14============== module=miner
Exception 0xc000001d 0x0 0x0 0x7ffdf9aad9b4
PC=0x7ffdf9aad9b4

runtime: unknown pc 0x7ffdf9aad9b4
stack: frame={sp:0x204c830, fp:0x0} stack=[0x0,0x204fdc0)
000000000204c730:  0000000000000000  0000000000000000
000000000204c740:  000005c0fffffb30  000004d0fffffb30
000000000204c750:  00000000000000f0  0000000000000000
000000000204c760:  00000000c000001d  0000000000000000
000000000204c770:  00007ffdf9aad9b4  0000000000000000
000000000204c780:  0000000000000000  0000000000000000
000000000204c790:  0000000000000000  0000000000000000
000000000204c7a0:  0000000000000000  0000000000000000
000000000204c7b0:  0000000000000000  0000000000000000
000000000204c7c0:  0000000000000000  0000000000000000
000000000204c7d0:  0000000000000000  0000000000000000
000000000204c7e0:  0000000000000000  0000000000000000
000000000204c7f0:  0000000000000000  0000000000000040
000000000204c800:  00007ffdf9aad9b4  000000000204d740
000000000204c810:  000000000204d760  000000000204c830
000000000204c820:  000000000204d740  00007ffdf9aad99c
000000000204c830: <000000000204d720  000000000204d760
000000000204c840:  000000000204cbb0  000000000204d730
000000000204c850:  000000000204d720  000000000204d760
000000000204c860:  0000000000000001  000000000204d870
000000000204c870:  0000000000000000  0000000000000020
000000000204c880:  00000000ffffffff  00007ffdf998724c
000000000204c890:  0000000012628e48  00000000ffffffff
000000000204c8a0:  0000000012628c38  0000000000000000
000000000204c8b0:  0000000000000001  00007ffdf9aae4cd
000000000204c8c0:  0000000000000040  0000000000000001
000000000204c8d0:  0000000012120c90  0000000000000001
000000000204c8e0:  0000000000000005  0000000000000001
000000000204c8f0:  0000000000000000  0000000000000000
000000000204c900:  0000000000000000  00007ffd00000040
000000000204c910:  ffffffff00000040  ffffffff00ffffff
000000000204c920:  0000000000000040  00000000ff000000
runtime: unknown pc 0x7ffdf9aad9b4
stack: frame={sp:0x204c830, fp:0x0} stack=[0x0,0x204fdc0)
000000000204c730:  0000000000000000  0000000000000000
000000000204c740:  000005c0fffffb30  000004d0fffffb30
000000000204c750:  00000000000000f0  0000000000000000
000000000204c760:  00000000c000001d  0000000000000000
000000000204c770:  00007ffdf9aad9b4  0000000000000000
000000000204c780:  0000000000000000  0000000000000000
000000000204c790:  0000000000000000  0000000000000000
000000000204c7a0:  0000000000000000  0000000000000000
000000000204c7b0:  0000000000000000  0000000000000000
000000000204c7c0:  0000000000000000  0000000000000000
000000000204c7d0:  0000000000000000  0000000000000000
000000000204c7e0:  0000000000000000  0000000000000000
000000000204c7f0:  0000000000000000  0000000000000040
000000000204c800:  00007ffdf9aad9b4  000000000204d740
000000000204c810:  000000000204d760  000000000204c830
000000000204c820:  000000000204d740  00007ffdf9aad99c
000000000204c830: <000000000204d720  000000000204d760
000000000204c840:  000000000204cbb0  000000000204d730
000000000204c850:  000000000204d720  000000000204d760
000000000204c860:  0000000000000001  000000000204d870
000000000204c870:  0000000000000000  0000000000000020
000000000204c880:  00000000ffffffff  00007ffdf998724c
000000000204c890:  0000000012628e48  00000000ffffffff
000000000204c8a0:  0000000012628c38  0000000000000000
000000000204c8b0:  0000000000000001  00007ffdf9aae4cd
000000000204c8c0:  0000000000000040  0000000000000001
000000000204c8d0:  0000000012120c90  0000000000000001
000000000204c8e0:  0000000000000005  0000000000000001
000000000204c8f0:  0000000000000000  0000000000000000
000000000204c900:  0000000000000000  00007ffd00000040
000000000204c910:  ffffffff00000040  ffffffff00ffffff
000000000204c920:  0000000000000040  00000000ff000000

goroutine 1 [syscall]:
github.com/Qitmeer/go-opencl/cl._Cfunc_clBuildProgram(0xab6bc90, 0xc000000001, 0xc0000060e8, 0x0, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:348 +0x54
github.com/Qitmeer/go-opencl/cl.(*Program).BuildProgram.func2(0xc0003f4ba0, 0x1, 0xc0000060e8, 0x0, 0x1)
        D:/miner/gosrc/src/github.com/Qitmeer/go-opencl/cl/program.go:59 +0xb8
github.com/Qitmeer/go-opencl/cl.(*Program).BuildProgram(0xc0003f4ba0, 0xc000087e10, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        D:/miner/gosrc/src/github.com/Qitmeer/go-opencl/cl/program.go:59 +0x97
qitmeer-miner/symbols/qitmeer.(*Cuckaroo).InitDevice(0xc000049500)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuckaroo.go:133 +0x8ac
qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run(0xc0000b0000)
        D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:112 +0x3cf
main.main()
        D:/miner/gosrc/src/qitmeer-miner/main.go:45 +0xe0

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        D:/go1.12.1.windows-amd64/go/src/runtime/sigqueue.go:139 +0xa3
os/signal.loop()
        D:/go1.12.1.windows-amd64/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
        D:/go1.12.1.windows-amd64/go/src/os/signal/signal_unix.go:29 +0x48

goroutine 20 [chan receive]:
main.main.func1(0xc000044360)
        D:/miner/gosrc/src/qitmeer-miner/main.go:37 +0x3b
created by main.main
        D:/miner/gosrc/src/qitmeer-miner/main.go:36 +0xc3
rax     0x12628e48
rbx     0x204d720
rcx     0x204d720
rdi     0x204d740
rsi     0x204d760
rbp     0x204c930
rsp     0x204c830
r8      0x0
r9      0x204d730
r10     0x40
r11     0x204b900
r12     0x0
r13     0x12628c38
r14     0x0
r15     0x4
rip     0x7ffdf9aad9b4
rflags  0x10287
cs      0x33
fs      0x53
gs      0x2b

C:\download\win-miner>

**环境信息 (请尽可能提供完整信息):**
- 操作系统 Windows 10-企业版 LTSC （纯净版）
- 显卡 [e.g. GTX 2070S]x1 
-主板：昂达1800 6卡
-硬盘：SSD
内存：4G
  ```

- 命令行参数或配置文件 （solo.conf）
# the miner config file

#[log] miner submit log
#minerlog=

#[Necessary Config]
#coin
symbol=PMEER

#pow type cuckaroo|blake2bd|cuckatoo
pow=cuckaroo
#[Solo Config]

#miner address
mineraddress=TmQ3GgoAPrtyoAENtsKJtt9VHNcep8wnSuB


# node rpc server
rpcserver=https://127.0.0.1:18131
# rpcserver=192.168.52.33:1234

# node rpc user
rpcuser=test 
# node rpc password
rpcpass=test 
#not tls
#notls=true
#rpccert
#rpccert=rpc.cert

#[Necessary Config]
#network privnet|testnet|mainnet|mixnet
network=testnet
#trimmerCount
trimmerTimes=14
# Intensities (the work size is 2^intensity) up to device
intensity=24
# The explicitly declared sizes of the work to do up to device (overrides intensity)
worksize=256
# cpuminer=true
use_devices=0
log_level=debug
#stats_server=127.0.0.1:1235
edge_bits = 24
max_sig_count=4000
cuda=false

(config.conf)
testnet=true 
datadir=./data 
logdir=./data 
listen=0.0.0.0:18130 
rpclisten=0.0.0.0:18131 
rpcuser=test 
rpcpass=test 
notls=false 
printorigin=false 
debuglevel=info 

**其它备注**
任何其它需要说明的问题。

**Comment by jamesvan2019** [comment]
> **BUG描述**
> 挖矿闪退，报错
> 
> **重现步骤**
> 必现
> 
> **预期的行为**
> 不应该有报错信息
> 
> **截屏(如有)**
> 不知道怎么弄。
> 我复制下报错信息：
> C:\download\win-miner>qitmeer-miner.exe --version
> Qitmeer Miner Version:0.3.4(Go version go1.12.1)
> 
> C:\download\win-miner>qitmeer-miner.exe -C solo.conf
> 2019-12-18|15:19:05.425 [INFO ] Platform:NVIDIA CUDA DeviceID:# 0 DeviceName:GeForce RTX 2070 SUPER MaxAllocSize:2048.00 MB MaxMemSize:8192.00 MB module=miner
> 2019-12-18|15:19:05.673 [INFO ] solo miner start module=miner
> 2019-12-18|15:19:06.201 [DEBUG] ==============Mining Cuckaroo: deviceID:0 edge bits:24 trimmerTimes:14============== module=miner
> Exception 0xc000001d 0x0 0x0 0x7ffdf9aad9b4
> PC=0x7ffdf9aad9b4
> 
> runtime: unknown pc 0x7ffdf9aad9b4
> stack: frame={sp:0x204c830, fp:0x0} stack=[0x0,0x204fdc0)
> 000000000204c730: 0000000000000000 0000000000000000
> 000000000204c740: 000005c0fffffb30 000004d0fffffb30
> 000000000204c750: 00000000000000f0 0000000000000000
> 000000000204c760: 00000000c000001d 0000000000000000
> 000000000204c770: 00007ffdf9aad9b4 0000000000000000
> 000000000204c780: 0000000000000000 0000000000000000
> 000000000204c790: 0000000000000000 0000000000000000
> 000000000204c7a0: 0000000000000000 0000000000000000
> 000000000204c7b0: 0000000000000000 0000000000000000
> 000000000204c7c0: 0000000000000000 0000000000000000
> 000000000204c7d0: 0000000000000000 0000000000000000
> 000000000204c7e0: 0000000000000000 0000000000000000
> 000000000204c7f0: 0000000000000000 0000000000000040
> 000000000204c800: 00007ffdf9aad9b4 000000000204d740
> 000000000204c810: 000000000204d760 000000000204c830
> 000000000204c820: 000000000204d740 00007ffdf9aad99c
> 000000000204c830: <000000000204d720 000000000204d760
> 000000000204c840: 000000000204cbb0 000000000204d730
> 000000000204c850: 000000000204d720 000000000204d760
> 000000000204c860: 0000000000000001 000000000204d870
> 000000000204c870: 0000000000000000 0000000000000020
> 000000000204c880: 00000000ffffffff 00007ffdf998724c
> 000000000204c890: 0000000012628e48 00000000ffffffff
> 000000000204c8a0: 0000000012628c38 0000000000000000
> 000000000204c8b0: 0000000000000001 00007ffdf9aae4cd
> 000000000204c8c0: 0000000000000040 0000000000000001
> 000000000204c8d0: 0000000012120c90 0000000000000001
> 000000000204c8e0: 0000000000000005 0000000000000001
> 000000000204c8f0: 0000000000000000 0000000000000000
> 000000000204c900: 0000000000000000 00007ffd00000040
> 000000000204c910: ffffffff00000040 ffffffff00ffffff
> 000000000204c920: 0000000000000040 00000000ff000000
> runtime: unknown pc 0x7ffdf9aad9b4
> stack: frame={sp:0x204c830, fp:0x0} stack=[0x0,0x204fdc0)
> 000000000204c730: 0000000000000000 0000000000000000
> 000000000204c740: 000005c0fffffb30 000004d0fffffb30
> 000000000204c750: 00000000000000f0 0000000000000000
> 000000000204c760: 00000000c000001d 0000000000000000
> 000000000204c770: 00007ffdf9aad9b4 0000000000000000
> 000000000204c780: 0000000000000000 0000000000000000
> 000000000204c790: 0000000000000000 0000000000000000
> 000000000204c7a0: 0000000000000000 0000000000000000
> 000000000204c7b0: 0000000000000000 0000000000000000
> 000000000204c7c0: 0000000000000000 0000000000000000
> 000000000204c7d0: 0000000000000000 0000000000000000
> 000000000204c7e0: 0000000000000000 0000000000000000
> 000000000204c7f0: 0000000000000000 0000000000000040
> 000000000204c800: 00007ffdf9aad9b4 000000000204d740
> 000000000204c810: 000000000204d760 000000000204c830
> 000000000204c820: 000000000204d740 00007ffdf9aad99c
> 000000000204c830: <000000000204d720 000000000204d760
> 000000000204c840: 000000000204cbb0 000000000204d730
> 000000000204c850: 000000000204d720 000000000204d760
> 000000000204c860: 0000000000000001 000000000204d870
> 000000000204c870: 0000000000000000 0000000000000020
> 000000000204c880: 00000000ffffffff 00007ffdf998724c
> 000000000204c890: 0000000012628e48 00000000ffffffff
> 000000000204c8a0: 0000000012628c38 0000000000000000
> 000000000204c8b0: 0000000000000001 00007ffdf9aae4cd
> 000000000204c8c0: 0000000000000040 0000000000000001
> 000000000204c8d0: 0000000012120c90 0000000000000001
> 000000000204c8e0: 0000000000000005 0000000000000001
> 000000000204c8f0: 0000000000000000 0000000000000000
> 000000000204c900: 0000000000000000 00007ffd00000040
> 000000000204c910: ffffffff00000040 ffffffff00ffffff
> 000000000204c920: 0000000000000040 00000000ff000000
> 
> goroutine 1 [syscall]:
> github.com/Qitmeer/go-opencl/cl._Cfunc_clBuildProgram(0xab6bc90, 0xc000000001, 0xc0000060e8, 0x0, 0x0, 0x0, 0x0)
> _cgo_gotypes.go:348 +0x54
> github.com/Qitmeer/go-opencl/cl.(*Program).BuildProgram.func2(0xc0003f4ba0, 0x1, 0xc0000060e8, 0x0, 0x1)
> D:/miner/gosrc/src/github.com/Qitmeer/go-opencl/cl/program.go:59 +0xb8
> github.com/Qitmeer/go-opencl/cl.(*Program).BuildProgram(0xc0003f4ba0, 0xc000087e10, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
> D:/miner/gosrc/src/github.com/Qitmeer/go-opencl/cl/program.go:59 +0x97
> qitmeer-miner/symbols/qitmeer.(*Cuckaroo).InitDevice(0xc000049500)
> D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/pow_cuckaroo.go:133 +0x8ac
> qitmeer-miner/symbols/qitmeer.(*QitmeerRobot).Run(0xc0000b0000)
> D:/miner/gosrc/src/qitmeer-miner/symbols/qitmeer/robot.go:112 +0x3cf
> main.main()
> D:/miner/gosrc/src/qitmeer-miner/main.go:45 +0xe0
> 
> goroutine 19 [syscall]:
> os/signal.signal_recv(0x0)
> D:/go1.12.1.windows-amd64/go/src/runtime/sigqueue.go:139 +0xa3
> os/signal.loop()
> D:/go1.12.1.windows-amd64/go/src/os/signal/signal_unix.go:23 +0x29
> created by os/signal.init.0
> D:/go1.12.1.windows-amd64/go/src/os/signal/signal_unix.go:29 +0x48
> 
> goroutine 20 [chan receive]:
> main.main.func1(0xc000044360)
> D:/miner/gosrc/src/qitmeer-miner/main.go:37 +0x3b
> created by main.main
> D:/miner/gosrc/src/qitmeer-miner/main.go:36 +0xc3
> rax 0x12628e48
> rbx 0x204d720
> rcx 0x204d720
> rdi 0x204d740
> rsi 0x204d760
> rbp 0x204c930
> rsp 0x204c830
> r8 0x0
> r9 0x204d730
> r10 0x40
> r11 0x204b900
> r12 0x0
> r13 0x12628c38
> r14 0x0
> r15 0x4
> rip 0x7ffdf9aad9b4
> rflags 0x10287
> cs 0x33
> fs 0x53
> gs 0x2b
> 
> C:\download\win-miner>
> 
> **环境信息 (请尽可能提供完整信息):**
> 
> * 操作系统 Windows 10-企业版 LTSC （纯净版）
> * 显卡 [e.g. GTX 2070S]x1
>   -主板：昂达1800 6卡
>   -硬盘：SSD
>   内存：4G
>   ```
>   
>   ```
> * 命令行参数或配置文件 （solo.conf）
> 
> # the miner config file
> #[log] miner submit log
> #minerlog=
> 
> #[Necessary Config]
> #coin
> symbol=PMEER
> 
> #pow type cuckaroo|blake2bd|cuckatoo
> pow=cuckaroo
> #[Solo Config]
> 
> #miner address
> mineraddress=TmQ3GgoAPrtyoAENtsKJtt9VHNcep8wnSuB
> 
> # node rpc server
> rpcserver=https://127.0.0.1:18131
> 
> # rpcserver=192.168.52.33:1234
> # node rpc user
> rpcuser=test
> 
> # node rpc password
> rpcpass=test
> #not tls
> #notls=true
> #rpccert
> #rpccert=rpc.cert
> 
> #[Necessary Config]
> #network privnet|testnet|mainnet|mixnet
> network=testnet
> #trimmerCount
> trimmerTimes=14
> 
> # Intensities (the work size is 2^intensity) up to device
> intensity=24
> 
> # The explicitly declared sizes of the work to do up to device (overrides intensity)
> worksize=256
> 
> # cpuminer=true
> use_devices=0
> log_level=debug
> #stats_server=127.0.0.1:1235
> edge_bits = 24
> max_sig_count=4000
> cuda=false
> 
> (config.conf)
> testnet=true
> datadir=./data
> logdir=./data
> listen=0.0.0.0:18130
> rpclisten=0.0.0.0:18131
> rpcuser=test
> rpcpass=test
> notls=false
> printorigin=false
> debuglevel=info
> 
> **其它备注**
> 任何其它需要说明的问题。

`cpuminer=true` change `cpuminer=false`  will be fixed, some machines  opencl sdk cannot have the access to use cpu devices

**Comment by foqer** [comment]
不是因为cpuminer=true的因素，粘贴到这里的时候因为编辑器的原因前面的#被转义了，其实我的配置文件cpuminer=true前面有一个“#”。而且我把#去掉再改成cpuminer=false，一样情况，闪退！

**Comment by foqer** [comment]
```
# the miner config file

#[log] miner submit log
#minerlog=

#[Necessary Config]
#coin
symbol=PMEER

#pow type cuckaroo|blake2bd|cuckatoo
pow=cuckaroo
#[Solo Config]

#miner address
mineraddress=TmQ3GgoAPrtyoAENtsKJtt9VHNcep8wnSuB


# node rpc server
rpcserver=https://127.0.0.1:18131
# rpcserver=192.168.52.33:1234

# node rpc user
rpcuser=test 
# node rpc password
rpcpass=test 
#not tls
#notls=true
#rpccert
#rpccert=rpc.cert

#[Necessary Config]
#network privnet|testnet|mainnet|mixnet
network=testnet
#trimmerCount
trimmerTimes=14
# Intensities (the work size is 2^intensity) up to device
intensity=24
# The explicitly declared sizes of the work to do up to device (overrides intensity)
worksize=256
#cpuminer=true
use_devices=0
log_level=debug
#stats_server=127.0.0.1:1235
edge_bits = 24
max_sig_count=4000
cuda=false

```
