### ISSUE TITLE
矿池 set_diffculty 处理有问题

### ISSUE THREAD

**Issue by neal-zhu** [Qitmeer/qitmeer-miner#146]
**BUG描述**
矿池 set_diffculty 32，miner 在验证 diff 的时候，使用的是 1(cuckraoo)

**重现步骤**
如何可以使该BUG出现的步骤:
矿池 set_diffculty 设置为 32

**预期的行为**
预期提交的 share 难度不低于 32，实际是随便提交，拒绝率很高

**环境信息 (请尽可能提供完整信息):**
与环境无关，miner 代码逻辑有问题

- qitmeer-miner 版本 [0.3.4]

**其它备注**
相关代码见  symbols/qitmeer/stratum.go:263:
```go
//  pow type 为 cuckraoo 时 s.CalcBasePowLimit() == big.NewInt(1)
s.Target, _ := common.DiffToTarget(s.Diff, s.CalcBasePowLimit())
```
symbols/qitmeer/submitheader.go:50 
```go
this.TargetDiff = big.NewInt(int64(work.stra.Diff))
```
symbols/qitmeer/pow_cuckraoo.go:391
```go
if diff.Cmp(this.header.TargetDiff)  < 0 { // 这里使用的是错误的结果
```

**Comment by jamesvan2019** [comment]
是的 谢谢你的建议 ，已经发现了这个问题 已经修复了 下个版本

**Comment by rlinxy** [comment]
解决了的话，能否放个新的release？谢谢

**Comment by jamesvan2019** [comment]
> 解决了的话，能否放个新的release？谢谢

ok

**Comment by jamesvan2019** [comment]
[miner-0.3.6](https://github.com/Qitmeer/qitmeer-miner/releases/tag/v0.3.6) fix the pool diff
