### ISSUE TITLE
qitmeer-miner stratum example

### ISSUE THREAD

**Issue by AlexSpain** [Qitmeer/qitmeer-miner#152]
Hi, 

Can you share please stratum example for qitmeer-miner

Thank you.

**Comment by jamesvan2019** [comment]
`qitmeer-miner` follow the standard stratum protocol.

**Comment by jamesvan2019** [comment]
> Hi,
> 
> Can you share please stratum example for qitmeer-miner
> 
> Thank you.

see [here](https://github.com/Qitmeer/qitmeer/issues/228)
