### ISSUE TITLE
PoW naming (cuckaroo <--> cuckoo)

### ISSUE THREAD

**Issue by Lolliedieb** [Qitmeer/qitmeer-miner#157]
Hey there,

i got a question about the naming of the PoW schemes used here. The naming for cuckatoo-29 seems correct, but I wonder why you named the more lightweight PoW cuckARoo-24 although from implementation side it lacks the dipblock type of seeding, that is characteristic for all cuckaroo based pows (Cuckaroo, CuckarooD and CuckarooM). See here:

https://github.com/tromp/cuckoo/blob/master/src/cuckaroo/mean.cu 

So in my opinion the PoW implemented in this miner rather matches Cuckoo-24 instead of CuckARoo-24.

**Comment by jamesvan2019** [comment]
yes  , our original plan was to cuckaroo, but now it's really cuckoo
