### ISSUE TITLE
qitmeer-miner compile problem

### ISSUE THREAD

**Issue by vigoss30611** [Qitmeer/qitmeer-miner#164]
When I compile with qitmeer-miner in win10, I get log:
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcudacuckoo
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcudacuckoo
collect2.exe: error: ld returned 1 exit status
I guess maybe I need libcudacuckoo.a in mingw32, so I compile libcudacuckoo.a from cudacuckoo.dll(from qitmeer-miner-lib.zip),
cmd: dlltool.exe -D .\cudacuckoo.dll  -l ./libcudacuckoo.a
but the libcudacuckoo.a only 2K, it seems not right.
so I try cmd dlltool.exe -D .\cudacuckoo.dll  -l ./libcudacuckoo.a -v
log show: 
C:\msys64\mingw64\bin\dlltool.exe:  dll  '.\cudacuckoo.dll'
C:\msys64\mingw64\bin\dlltool.exe: C:\msys64\mingw64\bin\as
C:\msys64\mingw64\bin\dlltool.exe:
C:\msys64\mingw64\bin\dlltool.exe:
C:\msys64\mingw64\bin\dlltool.exe: ./libcudacuckoo.a
C:\msys64\mingw64\bin\dlltool.exe: C:\msys64\mingw64\bin\as   -o doljbh.o doljbh.s
C:\msys64\mingw64\bin\dlltool.exe: C:\msys64\mingw64\bin\as   -o doljbt.o doljbt.s
C:\msys64\mingw64\bin\dlltool.exe:  lib
not show any problem...
So how to solve this problem. Please give me a favor

**Comment by jamesvan2019** [comment]
> When I compile with qitmeer-miner in win10, I get log:
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcudacuckoo
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcudacuckoo
> collect2.exe: error: ld returned 1 exit status
> I guess maybe I need libcudacuckoo.a in mingw32, so I compile libcudacuckoo.a from cudacuckoo.dll(from qitmeer-miner-lib.zip),
> cmd: dlltool.exe -D .\cudacuckoo.dll -l ./libcudacuckoo.a
> but the libcudacuckoo.a only 2K, it seems not right.
> so I try cmd dlltool.exe -D .\cudacuckoo.dll -l ./libcudacuckoo.a -v
> log show:
> C:\msys64\mingw64\bin\dlltool.exe: dll '.\cudacuckoo.dll'
> C:\msys64\mingw64\bin\dlltool.exe: C:\msys64\mingw64\bin\as
> C:\msys64\mingw64\bin\dlltool.exe:
> C:\msys64\mingw64\bin\dlltool.exe:
> C:\msys64\mingw64\bin\dlltool.exe: ./libcudacuckoo.a
> C:\msys64\mingw64\bin\dlltool.exe: C:\msys64\mingw64\bin\as -o doljbh.o doljbh.s
> C:\msys64\mingw64\bin\dlltool.exe: C:\msys64\mingw64\bin\as -o doljbt.o doljbt.s
> C:\msys64\mingw64\bin\dlltool.exe: lib
> not show any problem...
> So how to solve this problem. Please give me a favor

## Two Solutions:
- 1. get cudacuckoo.dll in  https://github.com/Qitmeer/qitmeer-miner/releases/tag/v0.5.0
  - put it in current directory or %system%
- 2. you can compile it by read this https://github.com/Qitmeer/qitmeer-miner/tree/master/lib/cuda

**Comment by vigoss30611** [comment]
get cudacuckoo.dll in https://github.com/Qitmeer/qitmeer-miner/releases/tag/v0.5.0，and 
try cmd dlltool.exe -D .\cudacuckoo.dll -l ./libcudacuckoo.a， only get 4k libcudacuckoo.a， 
it seems not right

**Comment by vigoss30611** [comment]
and I Put the 4K libcudacuckoo.a to mingw32, try go build, get
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b229\_x004.o: in function `_cgo_f4349b28d443_Cfunc_init_solver':
/tmp/go-build/cgo-gcc-prolog:61: undefined reference to `init_solver'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b229\_x004.o: in function `_cgo_f4349b28d443_Cfunc_run_solver':
/tmp/go-build/cgo-gcc-prolog:88: undefined reference to `run_solver'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b229\_x004.o: in function `_cgo_f4349b28d443_Cfunc_stop_solver':
/tmp/go-build/cgo-gcc-prolog:103: undefined reference to `stop_solver'
collect2.exe: error: ld returned 1 exit status

**Comment by jamesvan2019** [comment]
> and I Put the 4K libcudacuckoo.a to mingw32, try go build, get
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b229_x004.o: in function `_cgo_f4349b28d443_Cfunc_init_solver': /tmp/go-build/cgo-gcc-prolog:61: undefined reference to `init_solver'
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b229_x004.o: in function `_cgo_f4349b28d443_Cfunc_run_solver': /tmp/go-build/cgo-gcc-prolog:88: undefined reference to `run_solver'
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b229_x004.o: in function `_cgo_f4349b28d443_Cfunc_stop_solver': /tmp/go-build/cgo-gcc-prolog:103: undefined reference to `stop_solver'
> collect2.exe: error: ld returned 1 exit status

you can compilation dynamic
