### ISSUE TITLE
There was an anomaly in the excavation

### ISSUE THREAD

**Issue by 1617176084** [Qitmeer/qitmeer-miner#186]
I started mining after the main network nodes were successfully synchronized. I follow the tutorial in the current codebase and, when mining is turned on, return the following errors 
![image](https://user-images.githubusercontent.com/7008899/144363735-2139f9f2-61bc-48d3-a716-a357f51d9922.png)
![image](https://user-images.githubusercontent.com/7008899/144364014-c1d267c1-e43a-4e94-bb10-376e087a914c.png)
![image](https://user-images.githubusercontent.com/7008899/144364029-963cc0bd-9b57-461f-baf9-7d8fe6dbf1c9.png)

**Comment by dindinw** [comment]
Thanks for your interesting on mining on Qitmeer network. Currently if you want to mine on the `mainnet`, you have to use a dedicated ASCI miner. You can run the CPU miner for the testing purpose on the `testnet`.
