### ISSUE TITLE
为什么不能挖？

### ISSUE THREAD

**Issue by bbkbk222** [Qitmeer/qitmeer-miner#66]
![image](https://user-images.githubusercontent.com/48194218/66829754-9d95b100-ef86-11e9-97b6-e3f20205a93d.png)

**Comment by jamesvan2019** [comment]
solo挖矿，需要配置节点地址，这个问题是本地节点不存在，等pool挖矿之后开放，便可使用pool mining   ,看qitmeer.conf  开启 pool参数便是矿池地址 ，rpcserver是节点地址 ，需要solo挖矿，前往https://www.qitmeertalk.org/ 查看教程
