### ISSUE TITLE
fix broken links in the release page

### ISSUE THREAD

**Issue by dindinw** [Qitmeer/qitmeer-miner#81]
some links are obsoleted in the https://github.com/Qitmeer/qitmeer-miner/releases/tag/v0.2.4
ex : See [help](https://halalchain.github.io/docs/en/reference/qitmeer-miner/)
the updated help link :
https://qitmeer.github.io/docs/en/reference/qitmeer-miner/

**Comment by jamesvan2019** [comment]
Fixed
