### ISSUE TITLE
中文教程：windows系统qitmeer-miner编译及环境准备指导

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qitmeer-miner#88]
### 通用环境要求（附安装链接）
1. [Git 安装](https://git-scm.com/downloads)
2. [Go](https://golang.org/dl/) 版本 >= 1.12  //可能需要vpn
3. [Rust/Cargo](https://www.rust-lang.org/tools/install) >= 1.38.0

### 特殊环境要求 for windows

安装 [Build Tools for Visual Studio](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16)

安装过程中选择【 c++生成工具集】，如下图：

![image](https://user-images.githubusercontent.com/32875657/68102887-9d4a5f00-ff0f-11e9-8b82-7bd41672eec9.png)

### build 编译

1.  Get Source code 克隆代码到本地：

`git clone git@github.com:Qitmeer/qitmeer-miner.git` 或者`git clone https://github.com/Qitmeer/qitmeer-miner.git`

![image](https://user-images.githubusercontent.com/32875657/68103019-1e095b00-ff10-11e9-86b2-bb0fd9e05cb2.png)

2. Build the curkoo library 构建 cuckoo 库

```bash
$ cd qitmeer-miner  //打开 文件夹 qitmeer-miner
$ cd lib/cuckoo  //打开文件目录 lib/cuckoo
$ cargo build --release  //执行该命令构建 cuckoo 库
```

![image](https://user-images.githubusercontent.com/32875657/68103290-1a2a0880-ff11-11e9-85ab-bd2ebdfe4c54.png)

3. Build qitmeer-miner 构建qitmeer-miner

```bash
$ cd ..\..   //目录回退两层，回到qitmeer-miner文件价目录下
$ go build  //执行go build命令构建qitmeer-miner
```

4. Verify Build OK 确认编译是否成功

```bash
$ ./qitmeer-miner --version
```

注：该步骤反馈 无此标志：
![image](https://user-images.githubusercontent.com/32875657/68103768-1e572580-ff13-11e9-9fa7-281a7e9de837.png)
这个可能是程序中未设定此flag。

### Windows附加步骤
在执行第3步前，即 执行`go build`命令前，需先做下面这一步：
```bash
$ copy lib/cuckoo/target/release/cuckoo.dll to C:/Windows
```
手动复制文件目录：lib/cuckoo/target/release/ 下的文件 `cuckoo.dll ` 到 C盘目录 C:/Windows文件夹中，否则go build不成功，会报如下错误：

![image](https://user-images.githubusercontent.com/32875657/68103447-dc79af80-ff11-11e9-87f7-f3108284d009.png)

**Comment by blocklee** [comment]
这个是我按照自己的操作过程转换的中文版windows编译经验

**Comment by dindinw** [comment]
The README page updated to add a linker to the tutorial. the issue will be closed. We will try to improve our documentation site at https://qitmeer.github.io/docs, please feel free to take a look & add your contributions there. Thanks again for your wonderful work! 👍

**Comment by dindinw** [comment]
@blocklee please use the lastest code & verify again the version works 
```
$ ./qitmeer-miner --version
Qitmeer Miner Version:0.2.4
```
